version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cot_mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: car_order
    ports:
      - "3308:3306"
    volumes:
      - ./mysql/init-meta.sql:/docker-entrypoint-initdb.d/init-meta.sql:ro
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: cot_rabbitmq
    restart: always
    env_file: ./.env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  app:
    build: .
    container_name: cot_app
    restart: always
    depends_on:
      - mysql
      - rabbitmq
    env_file: ./.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/car_order?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_ROOT_PASSWORD}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      RABBITMQ_HOST: rabbitmq
      SPRING_JWT_SECRET: ${SPRING_JWT_SECRET}
      DB_MLP_HOST: ${DB_MLP_HOST}
      MLP_UPLOAD_URL: ${MLP_UPLOAD_URL}
      IMP_API_KEY: ${IMP_API_KEY}
      IMP_SECRET_KEY: ${IMP_SECRET_KEY}
    ports:
      - "8080:8080"

volumes:
  mysql_data:
  rabbitmq_data:

