scrape_configs:
  - job_name: 'car-order-traker'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      # - targets: ['localhost:8080']
      - targets: ['host.docker.internal:8080']