INSERT INTO masters (id,
                     business_number,
                     name,
                     phone_number,
                     email,
                     password,
                     address,
                     license,
                     role,
                     is_deleted,
                     deleted_at,
                     created_at,
                     updated_at)
VALUES (1,
        '123-45-67890', -- 두 계정이 같은 사업자 번호
        '마스터A',
        '010-1234-5678',
        'masterA@example.com',
        '$2b$10$zlKr2tiDpfkNgifvCglcg.c01kXBOJre3Th3v5jqyj2sbPzi66Rfu',
        '서울시 강남구 역삼동 1-1',
        'LIC-20250101',
        'MASTER',
        FALSE,
        NULL,
        NOW(),
        NOW()),
       (2,
        '123-45-67890', -- 같은 사업자 번호
        '마스터B',
        '010-2345-6789',
        'masterB@example.com',
        '$2b$10$zlKr2tiDpfkNgifvCglcg.c01kXBOJre3Th3v5jqyj2sbPzi66Rfu',
        '서울시 강남구 역삼동 2-2',
        'LIC-20250102',
        'MASTER',
        FALSE,
        NULL,
        NOW(),
        NOW()),
       (3,
        '987-65-43210', -- 다른 사업자 번호
        '마스터C',
        '010-3456-7890',
        'masterC@example.com',
        '$2b$10$zlKr2tiDpfkNgifvCglcg.c01kXBOJre3Th3v5jqyj2sbPzi66Rfu',
        '서울시 강남구 역삼동 3-3',
        'LIC-20250103',
        'MASTER',
        FALSE,
        NULL,
        NOW(),
        NOW());
