### 환경 변수
@host = http://localhost
@port = 8080
@baseUrl = {{host}}:{{port}}

### 주문 생성 -> 결제
### 주문 생성 -> 미결제 -> 주문 상태 변경
### 프론트가 있어야하는 경우여서 따로 작성 하지 않음

### 주문 생성
POST {{baseUrl}}/api/dealers/orders
Content-Type: application/json
Authorization: Bearer {{token}} # 로그인에서 저장된 토큰 가져옴

{
  "userEmail": "user01@example.com",
  "option": [
    1,
    2,
    4
  ],
  "modelId": 1,
  "address": "서울시 강남구..."
}

### 주문 수정
PATCH {{baseUrl}}/api/dealers/orders/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "address": null,
  "orderStatus": "COMPLETED"
}

### 주문 단건조회
GET {{baseUrl}}/api/orders/1
Authorization: Bearer {{token}}


### 주문 전체조회
GET {{baseUrl}}/api/orders
Authorization: Bearer {{token}}

### 주문 삭제
DELETE {{baseUrl}}/api/dealers/orders/1
Authorization: Bearer {{token}}